Add min bid to single nfts if greater then 0
deso-protocol/frontend pull request #447
Opened 2021-09-18 15:51 UTC by tijno

Too often get caught out when I see low last bid, click on make bid, and turns out min bid is way higher.

So added to @iPaulPro recent change to also show min bid if its greater than 0.

![20210918-GVkvgdxn](https://user-images.githubusercontent.com/69529928/133894664-dedd6b23-d8f7-413e-9c18-ccc5cb5b7056.png)

2021-09-22 22:04 UTC, lazynina requested changes

2021-09-22 22:04 UTC, lazynina commented on src/app/feed/feed-post/feed-post.component.ts
> +          if (this.nftEntryResponses[0].MinBidAmountNanos>0) {
```suggestion
          if (this.nftEntryResponses[0].MinBidAmountNanos > 0) {
```

2021-09-27 15:44 UTC, lazynina approved these changes

2021-09-27 17:46 UTC, maebeam approved these changes

2021-09-27 17:46 UTC, merged