simplify loops in GetMessages that handles encryption/decryption
deso-protocol/frontend pull request #533
Opened 2021-12-15 16:21 UTC by lazynina

2021-12-15 20:26 UTC, maebeam approved these changes

2021-12-16 02:05 UTC, AeonSw4n requested changes

2021-12-16 02:05 UTC, AeonSw4n commented on src/app/backend-api.service.ts
> +                threads.messages.forEach(
Shouldn't this be `threads.Messages` ?

2021-12-16 15:04 UTC, maebeam commented on src/app/backend-api.service.ts
> +                threads.messages.forEach(
Great catch. Same error above too

2021-12-16 18:07 UTC, AeonSw4n approved these changes

2021-12-16 18:18 UTC, merged