Add support for twitter images..
deso-protocol/frontend pull request #568
Opened 2022-03-28 19:28 UTC by AdityaChaudhary0005

this will show images hosted on twitter (they have link like pbs.twing.com ex: https://pbs.twimg.com/media/FO9LbSjaQAEFE26.jpg)

before 
![image](https://user-images.githubusercontent.com/55331140/160470352-bde7f317-fcc7-4680-9180-f9487a7892bc.png)

after
![image](https://user-images.githubusercontent.com/55331140/160470432-5168c8a3-ad78-44e9-a147-3afc1fd11803.png)

will be helpful for those projects which are building bridge between twitter and deso.

2022-03-28 20:16 UTC, tijno commented
probably worth adding to caddyfile in run repo too

2022-04-12 20:18 UTC, lazynina requested changes

2022-04-12 20:18 UTC, lazynina commented on Caddyfile
> +    *.twing.com
wow - thought I submitted this review 2 weeks ago. Apologies @AdityaChaudhary0005

2022-04-12 23:52 UTC, AdityaChaudhary0005 commented on Caddyfile
> +    *.twing.com
oh yes, just noticed it is *.twimg.com
thanks

2022-04-15 16:27 UTC, lazynina approved these changes

2022-04-15 16:27 UTC, merged