Add Embed Post option in Feed Post DropDown
deso-protocol/frontend pull request #609
Opened 2022-10-16 11:33 UTC by jsonpreet

Add Embed Post Option in Feed Post DropDown. It Helps users who have their own websites.

2022-10-17 18:59 UTC, lazynina requested changes

2022-10-17 18:59 UTC, lazynina commented on src/app/feed/feed-post-dropdown/feed-post-dropdown.component.html
> +      Embed {{ this.post.IsNFT ? "NFT" : "Post" }}
```suggestion
      Embed {{ post.IsNFT ? 'NFT' : 'Post' }}
```

2022-10-17 18:59 UTC, lazynina commented on src/app/feed/feed-post-dropdown/feed-post-dropdown.component.ts
> +      console.error("Embed failed:", err.message);
```suggestion
      console.error('Embed failed:', err.message);
```

2022-10-17 19:00 UTC, lazynina approved these changes

2022-10-17 19:00 UTC, merged

2022-10-18 15:57 UTC, jsonpreet commented
Thank You